name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run start script from local
        run: ./start.sh --from-local

      - name: Move
        run: mv UniQuizzesFinal $GITHUB_WORKSPACE

      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "${{ github.workspace }}/UniQuizzesFinal/json/**/*.json"

      - name: Pushes to another repository
        run: echo "Pushes to another repo"
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: UniQuizzesFinal
          destination-github-username: 'dag7dev'
          destination-repository-name: 'UniQuizzes'
          user-email: dag7@protonmail.com
          target-branch: gh-pages
